services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
    environment:
      - FRONTEND_ORIGIN=http://frontend:8501
      - CHROMA_PERSIST_DIR=/app/chroma_db

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000